version: '3.8'

services:
  app:
    build: .
    container_name: blood-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/blood_donation_application
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Vaibhav2034

  db:
    image: mysql:8
    container_name: blood_donation_application
    restart: always
    environment:
      MYSQL_DATABASE: blooddb
      MYSQL_ROOT_PASSWORD: Vaibhav2034
    ports:
      - "3307:3306"
