# Application Name
spring.application.name=Blood Donation Application

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/BLOOD_DONATION_APPLICATION?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Vaibhav2034

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=8080
